version: '3.4'

services:
  database:
    image: postgres:13.1-alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

volumes:
  postgres_data:
    name: postgres_data
