"""Migrate message

Revision ID: 1f024d06bc9e
Revises: 57665131a409
Create Date: 2021-10-12 23:34:49.573941

"""
from alembic import op
import sqlalchemy as sa


from models.utilities import UUID2STR, UTCDatetime

# revision identifiers, used by Alembic.
revision = '1f024d06bc9e'
down_revision = '57665131a409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('area', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
