"""Add PirRecords

Revision ID: 57665131a409
Revises: a9ff4d823afc
Create Date: 2021-08-12 15:14:01.940359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from models.utilities import UUID2STR, UTCDatetime

# revision identifiers, used by Alembic.
revision = '57665131a409'
down_revision = 'a9ff4d823afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pir_records',
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('device_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.alter_column('meter_data', 'total_consumption',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='kWh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meter_data', 'total_consumption',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='kWh')
    op.drop_table('pir_records')
    # ### end Alembic commands ###
